name: Sync images

on:
  workflow_dispatch:
  schedule:
    # every day at 7am & 7pm pacific
    - cron: "0 2,14 * * *"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./auth.yaml
          images_file: ./images.yaml
          version: latest
          proc: 20
        env:
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          quay-user: ${{ secrets.quay-user }}
          quay-user-pwd: ${{ secrets.quay-user-pwd }}
          ali-user: ${{ secrets.ali-user }}
          ali-user-pwd: ${{ secrets.ali-user-pwd }}
          hub-user: ${{ secrets.hub-user }}
          hub-user-pwd: ${{ secrets.hub-user-pwd }}
